# Generated by Django 4.2.5 on 2023-10-01 13:15

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('service', '0002_remove_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.customer')),
            ],
        ),
    ]
