# Generated by Django 4.2.5 on 2023-10-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_customer_service_date_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service.unit'),
        ),
    ]
