# Generated by Django 4.2.5 on 2023-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_inventory_alter_unit_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
