# Generated by Django 4.2.5 on 2023-10-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_inventory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
